- .github/CODEOWNERS
- MAINTAINERS.md
Signed-off-by: Sarat Vemulapalli <vemulapallisarat@gmail.com>
Adding Maintainers.md and Codeowners file.
Closes #17 
> Adding Maintainers and Codeowners file

- pom.xml
Signed-off-by: Marc Handalian <handalm@amazon.com>
Bumping to latest jackson version. Resolving https://github.com/opensearch-project/opensearch-oci-object-storage/security/dependabot/12.
dependabot.
> Bump jackson dependencies to 2.14.1

- pom.xml
No changes other than standardizing the indentation to 4 spaces throughout the pom.xml file.
> Fix indentation in pom.xml

- README.md
- oci-repository-plugin/src/main/resources/plugin-descriptor.properties
- pom.xml
We upgrade the opensearch version of OCI Object Storage repo from 1.2.4 to 1.3.8 to deal with security concerns for the repo (6 CVEs). 
Resolves #31 
> upgrade opensearch version to 1.3.8

- oci-repository-plugin/pom.xml
- pom.xml
This project is currently targeting Java 15 bytecode. Since Java 15 is EOL I tried to build with Java 17, but that needed the newer version of lombok to work correctly.
> Update lombok to 1.18.26

- .github/workflows/gradle.yml
- build.gradle
- oci-objectstorage-fixture/build.gradle
- oci-objectstorage-fixture/src/main/java/org/opensearch/fixtures/oci/NonJerseyServer.java
- oci-objectstorage-fixture/src/test/java/org/opensearch/fixtures/oci/FixtureTests.java
- oci-repository-plugin/build.gradle
- oci-repository-plugin/src/main/java/org/opensearch/repositories/oci/OciObjectStorageBlobStore.java
- oci-repository-plugin/src/main/java/org/opensearch/repositories/oci/OciObjectStorageClientSettings.java
- oci-repository-plugin/src/main/java/org/opensearch/repositories/oci/OciObjectStoragePlugin.java
- oci-repository-plugin/src/main/java/org/opensearch/repositories/oci/OciObjectStorageRepository.java
- oci-repository-plugin/src/main/java/org/opensearch/repositories/oci/OciObjectStorageService.java
- oci-repository-plugin/src/test/java/org/opensearch/repositories/oci/OciObjectStoragePluginIT.java
- oci-repository-plugin/src/test/java/org/opensearch/repositories/oci/OciObjectStoragePluginTests.java
- oci-repository-plugin/src/test/java/org/opensearch/repositories/oci/TestConstants.java
This change fixes the issue of transient dependency resolution for the OCI obcjectstorage plugin plus some cleanups.
1. Fix dependency resolution for SDK dependencies.
2. Add restIntegTest
3. cleanup and allow `build` to pass
_List any issues this PR will resolve, e.g. Closes [https://github.com/opensearch-project/opensearch-oci-object-storage/issues/35]._ 
> fix transient dependencies resolution and add external integration tests

- README.md
- build.gradle
- oci-repository-plugin/build.gradle
Upgrade OCI SDK to 3.7.0 and open search to 2.6.0
Closes https://github.com/opensearch-project/opensearch-oci-object-storage/issues/34.
> upgrade oci sdk and opensearch to 2.6.0

- oci-objectstorage-fixture/src/main/java/org/opensearch/fixtures/oci/OciHttpHandler.java
- oci-repository-plugin/src/main/java/org/opensearch/repositories/oci/OciObjectStorageBlobContainer.java
- oci-repository-plugin/src/test/java/org/opensearch/repositories/oci/OciObjectStorageBlobStoreTests.java
1. Fixing path bugs related to build key when blob name is used.
2. Fix fixture issue for head request when object is empty.
Previously when blobStoreContainer would call `public InputStream readBlob(String blobName, long position, long length)`
with a base path set, we would get a `404 object not found`
> fix path bugs, fix fixture issue with head request for empty objects

- build.gradle
- oci-objectstorage-fixture/build.gradle
- oci-repository-plugin/src/main/java/org/opensearch/repositories/oci/OciObjectStoragePlugin.java
- oci-repository-plugin/src/main/java/org/opensearch/repositories/oci/OciObjectStorageRepository.java
- oci-repository-plugin/src/test/java/org/opensearch/repositories/oci/OciObjectStoragePluginIT.java
- oci-repository-plugin/src/test/java/org/opensearch/repositories/oci/OciObjectStoragePluginTests.java
- Bump OpenSearch version to 2.7.0
- Bump SDK version to 3.10.0
- Bump Java version for `oci-objectstorage-fixture` to Java 19
- Refactor `import org.opensearch.common.xcontent.*` to `import org.opensearch.core.xcontent.*`
*Sidenote*: I tested this locally by performing a `./gradlew publishToMavenLocal` on a local `2.x` branch for OpenSearch and tested the changes using the version `opensearch_version = System.getProperty("opensearch.version", "2.7.0-SNAPSHOT")`
We might need to cut a `2.7.0` tag for OpenSearch before merging this in.
- Resolves #44 
For more information on following Developer Certificate of Origin and signing off your commits, please check …
> Bump OpenSearch version to 2.7.0, SDK version to 3.10.0

- .github/CODEOWNERS
Add missing user to the CODEOWNERS file
_List any issues this PR will resolve, e.g. Closes [...]._ 
> Add missing user to the CODEOWNERS file

- build.gradle
- Bump `com.google.guava:guava` version from `31.1-jre` to `32.1.2-jre`
- Bump `com.diffplug.spotless` version from `6.17.0` to `6.21.0`
- Bump `oci-java-sdk` version from `3.10.0` to `3.24.0`
- Set dependency resolution strategy to use `guava` version `32.1.2-jre` for all Gradle projects.
Reference: https://github.com/opensearch-project/OpenSearch/commit/134257816acfa69db9b1a969e1854f4ece5a6e55
- Set dependency resolution strategy to use `netty-handler` version `4.1.94-Final` for sub-project `oci-repository-plugin`.
Reason:
There is a guava vulnerability CVE-2023-2976 (GHSA-7g45-4rm6-3mm3).
There are 3 use cases in the code base that use older version of guava:
1. A dependency of OCI Repository plugin to compile source code.
2. A dependency of Gradle plugin. `spotless`.
3. A dependency …
> Upgrade dependencies - guava 32.1.2-jre, spotless 6.21.0 and oci-java-sdk 3.24.0

- oci-repository-plugin/src/main/java/org/opensearch/repositories/oci/OciObjectStorageBlobStore.java
Increasing the timeout for putRequest to 60s from the current 5 seconds. Snapshot requests are failing in the OIC Dev environment due to the short timeout period for put requests.
_Describe what this change achieves._
_List any issues this PR will resolve, e.g. Closes [...]._ 
> Increase the timeout for putRequest to 60s from the current 5 seconds.

- .github/workflows/backport.yml
- .github/workflows/gradle.yml
- build.gradle
- oci-objectstorage-fixture/build.gradle
- oci-repository-plugin/src/test/java/org/opensearch/repositories/oci/OciObjectStoragePluginTests.java
Update main to 3.0.0 baseline
N/A
> Update main to 3.0.0 baseline

- MAINTAINERS.md
This commit moves me to emeritus as I don't expect to be actively involved in this repository in the foreseeable future.
> Move andrross to emeritus

- .github/CODEOWNERS
- MAINTAINERS.md
Also remove andrross from CODEOWNERS
> Fix markdown formatting

- .github/CODEOWNERS
- MAINTAINERS.md
- Moves kotwanikunal to Emeritus status
N/A
> Move kotwanikunal to emeritus

- .github/CODEOWNERS
- MAINTAINERS.md
Moving to Emeritus as I no longer intend to be an active maintainer of this repo.
> Moving saratvemulapalli to emeritus

- oci-objectstorage-fixture/src/main/java/org/opensearch/fixtures/oci/OciHttpHandler.java
- oci-objectstorage-fixture/src/test/java/org/opensearch/fixtures/oci/FixtureTests.java
- oci-repository-plugin/src/main/java/org/opensearch/repositories/oci/OciObjectStorageService.java
OCI Object Store mocking service was improperly replying and leading to connection leak on client side.
Fixed by supplying content length = -1 - means not response body and connection can be reused or closed.
Added UT to spot similar issue in future.
- [NA] New functionality includes testing.
- [NA] New functionality has been documented.
- [NA ] API changes companion pull request [created](https://github.com/opensearch-project/opensearch-api-specification/blob/main/DEVELOPER_GUIDE.md).
- [NA] Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose).
For more information on following Developer Certificate of Origin …
> Fix: ObjectStore client connections leaking during UTs

- build.gradle
- oci-objectstorage-client-shaded/build.gradle
- oci-objectstorage-fixture/build.gradle
- oci-objectstorage-fixture/src/main/java/org/opensearch/fixtures/oci/LocalBucket.java
- oci-objectstorage-fixture/src/main/java/org/opensearch/fixtures/oci/OciHttpHandler.java
- oci-objectstorage-fixture/src/test/java/org/opensearch/fixtures/oci/FixtureTests.java
- oci-repository-plugin/build.gradle
- oci-repository-plugin/src/main/java/org/opensearch/repositories/oci/OciObjectStorageBlobStore.java
- oci-repository-plugin/src/main/java/org/opensearch/repositories/oci/OciObjectStorageClientSettings.java
- oci-repository-plugin/src/main/java/org/opensearch/repositories/oci/OciObjectStoragePlugin.java
- oci-repository-plugin/src/main/java/org/opensearch/repositories/oci/OciObjectStorageService.java
- oci-repository-plugin/src/test/java/org/opensearch/repositories/oci/OciObjectStorageBlobStoreTests.java
- settings.gradle
OCI SDK had approximately 20 dependencies that can conflict with OpenSearch or another plugin that uses OCI SDK
Shading and relocating OCI SDK with 3rd party dependencies under org.opensearch.repositories.oci.sdk namespace
- [NA] New functionality includes testing.
- [NA] New functionality has been documented.
- [NA] API changes companion pull request [created](https://github.com/opensearch-project/opensearch-api-specification/blob/main/DEVELOPER_GUIDE.md).
- [NA] Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose).
For more information on following Developer Certificate of Origin and signing off your commits, …
> Relocating and shading OCI SDK

- build.gradle
- oci-repository-plugin/src/main/java/org/opensearch/repositories/oci/OciObjectStorageBlobStore.java
- oci-repository-plugin/src/main/java/org/opensearch/repositories/oci/OciObjectStorageService.java
- oci-repository-plugin/src/main/plugin-metadata/plugin-security.policy
- oci-repository-plugin/src/test/java/org/opensearch/repositories/oci/OciObjectStoragePluginTests.java
-  Security policies file refactored
- Cache key migrated from string to Settings object
- Cache cleanup in case of any exceptions
- OCI java SDK version updated to 3.30.0
Enabled retries as a workaround for #57 
- Exceptions from object store client in case of 401 or 404 response code closes the jersey client
- Subsequent retries would cause IllegalState exception
- Thus remove oci client instance from cache to enable retries in case of any exception 
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/opensearch-oci-object-storage/blob/main/CONTRIBUTING.md#developer-certific …
> Cache cleanup flow

- oci-repository-plugin/src/main/java/org/opensearch/repositories/oci/OciObjectStorageBlobContainer.java
- oci-repository-plugin/src/main/java/org/opensearch/repositories/oci/SocketAccess.java
- Fix the path to data files in OCI Object Storage
- Fix class cast error when trying to handle an exception
Resolves #[Issue number to be closed when this PR is merged]
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/opensearch-oci-object-storage/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).
> Fix the path to data files and class cast error while handling exception

- build.gradle
Netty version force to upgrade version to 4.1.118.Final
Resolves #[Issue number to be closed when this PR is merged]
https://github.com/opensearch-project/opensearch-oci-object-storage/issues/81
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/opensearch-oci-object-storage/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).
> Netty version update for CVE-2025-25193 CVE-2025-24970
